### PR TITLE
Only run auth on production environment

### PR DESCRIPTION
**Pull request by james-hinton**
NODE_ENV is set to production through `npm run build`

### CODE REVIEW

**Comment by ivica3730k** [comment]
Let me check does it build with that

**Comment by ivica3730k** [comment]
I am not sure it works, I have built the docker image locally and I should see the failing attempt to get to ./auth/me endpoint but it is not there

image

**Comment by james-hinton** [comment]
NODE_ENV is set to production through npm run build

**Comment by ivica3730k** [comment]
> NODE_ENV is set to production through npm run build

But it didn't work

**Comment by ivica3730k** [comment]
> NODE_ENV is set to production through npm run build

Try building the docker container

**Comment by james-hinton** [comment]
Okay I'll give it a go

**Comment by ivica3730k** [comment]
> Okay I'll give it a go

I tried this too but no luck

image

**Comment by ivica3730k** [comment]
I have a feeling that NODE_ENV only exists when you are running it with node. If you were to serve it with python3 -m http.server or something like that it would not exist.

Hence the need to introduce another variable:

image

**Comment by ivica3730k** [comment]
It still didn't work for me. If you guys want to dig in further. My knowledge of node is not deep enough it seems

**Comment by james-hinton** [comment]
Screenshot from 2023-05-18 13-40-26

**Comment by james-hinton** [comment]
i think maybe you built the wrong version or something, it works for me.

**Comment by ivica3730k** [comment]
How did ./auth/me on localhost return 200?

**Comment by ivica3730k** [comment]
push and merge it in then, I'l update terraform to pick it up

**Pull request merged**
