### PR TITLE
Add Shapefile Upload Feature

### PR DESCRIPTION
**Pull request by james-hinton**
Users can now upload a Shapefile via the new upload form, and the data from the file is then displayed on the map.

### CODE REVIEW

**Comment by james-hinton** [comment]
Fixes #26

**Comment by ivica3730k** [comment]
I can see that there is new endpoint in the backend for this, could you point me to that please?

**Comment by ivica3730k** [comment]
> > I can see that there is new endpoint in the backend for this, could you point me to that please?
> 
> https://github.com/SpatialDays/geo-projector
> 
> Have I got to route it through the backend?

Yes, we would need to deploy that microservice in a Kubernetes cluster and then route it trough backend, as our stac-portal-backend is point of termination for AD authentication

**Comment by ivica3730k** [comment]
Hope there are no big clashes, I have just changed some endpoint routes

**Comment by ivica3730k** [comment]
what a beast, never seen pr so big

**Pull request merged**
