### PR TITLE
fix: add trailing slashes for constructed urls

### PR DESCRIPTION
**Pull request by mountaincharlie**

### CODE REVIEW

**Comment by ivica3730k** [comment]
Did the delete operation work now? Sorry, working on ingester and cant test it right now.

Kind regards

Ivica Matic
Software Engineer
Spatial Days Ltd.

Unit 1 Hercules House, Calleva Park, Aldermaston, Berkshire, RG7 8DN
T. +44 (0)118 971 0035
M. +44 (0)7765 805737
E. ***@***.***
W. www.spatialdays.com

**Comment by mountaincharlie** [comment]
yup deleting all works
added the trailing slash to all url constructors and tested all the other functionality that i was able to

**Comment by ivica3730k** [comment]
Okay then, merge it in :)

Kind regards

Ivica Matic
Software Engineer
Spatial Days Ltd.

Unit 1 Hercules House, Calleva Park, Aldermaston, Berkshire, RG7 8DN
T. +44 (0)118 971 0035
M. +44 (0)7765 805737
E. ***@***.***
W. www.spatialdays.com

**Comment by ivica3730k** [comment]
There was some weird reason why we needed trailing slashes on the backend. I think Azure App Service does them, it is not standard in any way I think, we just sadly need to follow it? @james-hinton was it something like that?

**Comment by james-hinton** [comment]
> There was some weird reason why we needed trailing slashes on the backend. I think Azure App Service does them, it is not standard in any way I think, we just sadly need to follow it? @james-hinton was it something like that?

There was definitely something about a trailing slash being a must. Can't remember exactly, probably more likely to with the application itself rather than Azure App Service. I don't know though.

**Comment by james-hinton** [comment]
@mountaincharlie just fixed the merge conflict for you. Feel free to merge.

**Pull request merged**
