### PR TITLE
fix: used utc times

### PR DESCRIPTION
**Pull request by ivica3730k**
Can you check this out @mountaincharlie

### CODE REVIEW

**Comment by ivica3730k** [comment]
image

**Comment by ivica3730k** [comment]
ahh if we use .getTime() it will be unix timestamp for sure, let me fix it

**Comment by ivica3730k** [comment]
@mountaincharlie take a look now, ditched all GMT, UTC, whatnot timezones and just used UNIX time

**Comment by mountaincharlie** [comment]
so .getTime() gets the date in unix time?
nice one

**Comment by ivica3730k** [comment]
> 

Yep
image
i'll merge it in then

**Comment by mountaincharlie** [comment]
Also does 'timeToExpiry' in this bit change?
let timeToExpiry = tokenExpiryTimestampUnix - nowUnix;

Because if not could it be const rather than let?

**Comment by mountaincharlie** [comment]
if its readable enough and works i guess so
I wasn't totally sure if this would work tbh:
const tokenExpiryTimestampUnix = new Date(expires_on).getTime();

**Comment by ivica3730k** [comment]
Should do, edit it an merge in if you want :)

**Comment by ivica3730k** [comment]
I like to use this website for testing out snippets:

https://www.programiz.com/javascript/online-compiler/

**Comment by mountaincharlie** [comment]
Combined a few of those lines where it defines unix time and changed let to const as i think we're not redefining that variable anywhere 
I'll merge to staging

**Pull request merged**
